---
title: "passage_flows"
author: "Sam Bankston"
date: "December 26, 2018"
output: html_document
---

Load libraries with Kable

```{r message=FALSE, warning=FALSE}
library(lubridate)
library(tidyverse)
library(kableExtra)
library(waterData)
```


Use the waterData package to read in USGS flow data

```{r}
matilija_hl_flow <- importDVs(staid = "11114495", code = "00060") %>% mutate(Stream = "matilija_creek", date_time = ymd(dates), Year = year(date_time), Day = day(date_time)) %>% rename(flow = val) %>% select(Stream, date_time, flow, Day, Year) %>% summarize(low_flow = quantile(flow, probs = .50, na.rm = TRUE), high_flow = quantile(flow, probs = 0.99, na.rm = TRUE)) 

matilija_hl_flow %>% knitr::kable(caption = 'Matilija High and Low Fish Passage Flows', digits = 2) %>% kable_styling(bootstrap_options = c("striped", "condensed", "hover"), full_width = FALSE)

```


Read in all flow csv files

```{r message=FALSE, warning=FALSE}
all_flow <- list.files(pattern = "*flow.csv") %>% map_df(~read_csv(.)) %>% mutate(date_time = paste(Date, " ", Time), date_time = mdy_hms(date_time)) %>% rename(flow = Flow) %>% select(Stream, date_time, flow) %>% mutate(Day = date(date_time), Year = year(date_time))
```

Summary of daily flow values

```{r}
daily_flow_summary <- all_flow %>% filter(month(date_time) >= 1 & month(date_time) < 6) %>% group_by(Stream, Year, Day) %>% summarize(mean_daily_flow = mean(flow, na.rm = TRUE)) %>% ungroup()
```

Calculate low and high flow thresholds

```{r}
low_high <- daily_flow_summary %>% group_by(Stream) %>% summarize(low_flow = quantile(mean_daily_flow, probs = .50, na.rm = TRUE), high_flow = quantile(mean_daily_flow, probs = 0.99, na.rm = TRUE)) 

low_high %>% knitr::kable(caption = 'High and Low Fish Passage Flows', digits = 2) %>% kable_styling(bootstrap_options = c("striped", "condensed", "hover"), full_width = FALSE)

```

Top 5 mean daily flow values by stream 

```{r }
top_5 <- daily_flow_summary %>% select(- Year) %>% group_by(Stream) %>% top_n(n = 5, wt = mean_daily_flow) %>% arrange(Stream, desc(mean_daily_flow)) 

top_5 %>% knitr::kable(caption = 'Top 5 Mean Daily Flow Values', digits = 0 ) %>% kable_styling(bootstrap_options = c("striped", "condensed", "hover"), full_width = FALSE) %>% group_rows("", 1, 5) %>% group_rows("", 6, 10) %>% group_rows("", 11, 15) %>% group_rows("", 16, 20) %>% group_rows("", 21, 25) 
 
```

Number of years

```{r}
daily_flow_summary %>% group_by(Stream) %>% summarize(from = min(.$Year), to = max(.$Year), years_included = n_distinct(Year)) %>% kable(caption = "Number of Years Included") %>% kable_styling(bootstrap_options = c("striped", "condensed", "hover"), full_width = FALSE)
```



